# install.packages("data.table")
# install.packages("ggplot2")
# install.packages("jsonlite")
# install.packages("/home/hawkins/Documents/Cesar/blup_data/ASReml/ASReml_purchase/asreml-4.1.0.149-Ubuntu-18-R3.6.tar.gz", repos = NULL)
# install.packages("R/x86_64-pc-linux-gnu-library/3.6/asreml-4.1.0.149-Ubuntu-18-R4.0.tar.gz",repos = NULL)
rm(list = ls())
library(asreml)
# asreml.license.activate()
# devtools::install_github("AparicioJohan/MrBeanApp")
library(MrBean)
run_app()
